version: '3'
services:
  app:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: symfony
    container_name: symfony-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - mynetwork

  database:
    image: postgres:11-alpine
    container_name: symfony-db
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - 54320:5432
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    restart: unless-stopped
    ports:
      - 8010:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  database:
